spring:
  application:
    name: demo-importpic
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/helpplan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  devtools:
    restart:
      enabled: false
server:
  port: 8080
mybatis:
  type-aliases-package: com.sly.demo.importpic.model